<?php
$oppportunityList = $this->getListOpp;
$uselist = $this->uselist;
?>
<style>

    .label-tag{
        border: 1px solid #ddd; padding: 3px;
        background-color: #eee;
        color: #000;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        margin-right: 10px;margin-bottom: 5px;text-decoration: underline;
    }
    .tag-remove{cursor: pointer; }
    .tag-remove:hover{color: #777}
    .btn-matches{ margin-top: 20px;background-color: #20B2AA;padding: 7px 50px; color: #fff; border: 1px solid #eee}
    .btn-matches:hover{}
</style>
<script src="<?=URL_THEMES.'js/pocket.dashboard.js?vs=1';?>"></script>
<script type="text/javascript">
    var objdb = new pocketDashboard();
    var urlImage = '<?=URL_MEDIA_PHOTO;?>';
</script>

<div class="container" >

<!--Modal-->
<div class="modal fade" tabindex="-1" role="dialog" id="this-test-is-using" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-sm">
        <div class="modal-content modal-dialog-center">
            <div class="modal-header" style="border-bottom: none">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <div class="modal-title text-center" style="color: red">Can't detelet the test, because it's using</div>
            </div>
        </div>
    </div>
</div>
<!--END-->
<!-- Modal Add -->
<div class="modal fade" tabindex="-1" role="dialog" id="AddModalNotificationIndex" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content modal-dialog-center">
            <div class="modal-header login_modal_header">
                <button type="button" class="close cancel-notification" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title" id="myModalLabel">Add a Notification</h2>
            </div>
            <div class="modal-body login-modal" style="padding-top:0px">
                <div class="modal-body" style="padding-top:0px">
                    <form id="form-addnotification" name="form-addnotification">

                        <div class="col-md-12">
                            <div class="col-md-5" style="padding-left: 0px">
                                <div class="form-group">
                                    &nbsp;
                                    <select id= "receiverid" class="form-control">
                                        <option value="">Seclect a Receiver</option>
                                        <?php
                                        if(!empty($uselist)){
                                            foreach ($uselist as $k=>$useinfo){
                                                $receiverid_user = $useinfo['UserID'];
                                                $receiver_Name = $useinfo['firstname']." ".$useinfo['lastname'] ;
                                                if($clientIDLogin != $receiverid_user){
                                                    ?>
                                                    <option value="<?=$receiverid_user?>"><?=$receiver_Name?></option>
                                                <?php  }
                                            }
                                        }
                                        ?>

                                    </select>
                                </div>
                            </div>
                            <div class="col-md-7" style="padding-top: 21px; padding-left:0px">
                                <button data-loading-text="Loading..." class="btn btn-sm btn-primary" type="button" id="addReceiveEmail" >Add</button>
                            </div>
                        </div>
                        <div class="col-md-12">
                            To :
                            <div class="form-control" id="toTheseEmail">
                            </div>
                            <br>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <input value="" type="text" name="subjectNotification" id="subjectNotification" placeholder="Subject" class="form-control">
                                <br>
                                <textarea value="" type="text" name="contentNotification" id="contentNotification" placeholder="Content" class="form-control"></textarea>
                            </div>
                        </div>
                        <button id="addnotification" style="width:70px" type="button" class="btn btn-primary" data-loading-text="Loading..." onclick="javascript:objdb.addnotificationIndex()" >Add</button>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- End Model-->
<!-- deletemodal-->

<div class="modal fade" tabindex="-1" role="dialog" id="are-you-sure-you-want-to-delete" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-sm">
        <div class="modal-content modal-dialog-center">
            <div class="modal-header" style="border-bottom: none">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <div class="modal-title text-center">Are you sure you want to delete all selected messages?</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="test-act-remove">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<!--end-->

    <div class="row" style="padding-top: 20px">
        <div class="col-md-12"><h2 style="height: 48px"><a><strong>Dashboard</strong></a></h2></div>

    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <h2 style="height:60px; padding-top:7px; padding-left:30px"><strong>Welcome to Pocket Recruiter</strong></h2>
            </div>
        </div>
    </div>
    <div class="row">
        <?php
        if(empty($this->resultTestList) && empty($this->messageList) && empty($this->listCandidate)){
            $height = "height:200px";
        } else{
            $height = "height:400px";
        }
        ?>
       <div class="col-md-4">
           <div class="panel  panel-default" style="font-size:12px">
            <div class="panel-heading" style="background-color: #2a6496;color: #fff "><strong><a style="color: white" href='#'>New Matches</></a></strong></div>
            <div class="panel-body Contain-candidate-reload" style="<?=$height?>" >
                <?php
                if(!empty($this->listCandidate)&& count($this->listCandidate)>0){
                    foreach($this->listCandidate as $kk=>$listCandidateInfo){
                        if($listCandidateInfo['minimumsalary'] =="" && $listCandidateInfo['maximumsalary'] ==""){
                            $salary = "";
                        } else if($listCandidateInfo['minimumsalary'] ==""){
                            $salary = $listCandidateInfo['maximumsalary']."K";
                        } else if($listCandidateInfo['maximumsalary'] ==""){
                            $salary = $listCandidateInfo['minimumsalary']."K";
                        } else{
                            $salary = $listCandidateInfo['minimumsalary']."K"."-".$listCandidateInfo['maximumsalary']."K";
                        }

                       if($listCandidateInfo['image']==""){
                           $image = URL_MEDIA_PHOTO."avatar_none.jpg";
                       } else{
                            $image = URL_MEDIA_PHOTO.$listCandidateInfo['image'];
                        }

                        $companyName="";
                        if(!empty($listCandidateInfo['strTitle']) && count($listCandidateInfo['strTitle'])>0){
                            $i= 1;
                            $companyName = "";
                            foreach($listCandidateInfo['strTitle'] as $strTitleInfo){
                                if($i==1){
                                    $companyName = $strTitleInfo;
                                } else{
                                    $companyName = $companyName." , ".$strTitleInfo;
                                }
                                $i++;
                            }
                        }
                ?>
                        <div class="col-md-12" style="color: #777; margin-bottom: 10px;padding-left:0">
                            <div class="col-md-4" style="padding-left: 0"><img src="<?=$image?>" style="height: 85px; width:70px"></div>
                            <div class="col-md-8 text-bottom" style="vertical-align: text-bottom;padding-bottom: 0px; padding-left: 0">
                                <div style="color: #2a6496; font-weight: bold;vertical-align: text-bottom; padding-top:0"><?=$listCandidateInfo['firstname']?> &nbsp; <?=$listCandidateInfo['lastname']?></div>
                                <div style="vertical-align: text-bottom; padding-bottom: 0px">Opportunity:&nbsp;<?=$companyName?></div>
                               <div style="vertical-align: text-bottom; padding-bottom: 0px">Expected Salary:&nbsp;<?=$salary?></div>
                                <div style="vertical-align: text-bottom; padding-bottom: 0px"> District from job:&nbsp;
                                    <?php
                                    if($listCandidateInfo['tralveldistanceinmiles'] >1){
                                        echo $listCandidateInfo['tralveldistanceinmiles']."miles";
                                    } else if($listCandidateInfo['tralveldistanceinmiles']== 1){
                                        echo $listCandidateInfo['tralveldistanceinmiles']."mile";
                                    }
                                    ?>
                                </div>
                                <div style="vertical-align: text-bottom; padding-bottom: 0px">Mobile:&nbsp;<?=$listCandidateInfo['PhoneNumber']?></div>
                            </div>
                        </div>
                    <?php
                    }
                }
                ?>

           </div>
           </div>
       </div>
        <div class="col-md-4">
            <div class="panel  panel-default" style="font-size:12px">
                <div class="panel-heading" style="background-color: #2a6496;color: #fff "><strong><a style="color: white" href='#'>Pocket Recruiter Notifications</a></strong></div>
                <div class="panel-body"  style="<?=$height?>" >

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>
                                    <span class="pull-left">
                                        <label><input id="Index-Check-All" type="checkbox" name="" value=""/> Check All</label>
                                    </span>
                                    <span class="pull-right"><span class="dropdown">
                                       Action<span style="cursor:pointer; width:10px; height:2px" data-toggle="dropdown" class="caret"></span>
                                        <ul  class="dropdown-menu" role="menu">
                                            <li><a id="test-act-assign" data-toggle="modal" data-target="#AddModalNotificationIndex" href="javascript: void(0)">Compose</a></li>
                                            <!--<li><a id="test-act-remove" href="javascript: void(0)">Delete</a></li>-->
                                            <li><a data-toggle="modal" data-target="#are-you-sure-you-want-to-delete" href="javascript: void(0);">Delete</a></li>
                                        </ul>
                                    </span></span>
                                </th>
                            </tr>
                            </thead>
                            <tbody id="notification-list">
                            <?php
                            foreach($this->messageList as $item){ ?>
                                <tr class="notification-ischeck">
                                    <td><span style="font-weight: bold"><input type="checkbox" value="<?=$item['NotificationID']?>" class="Index-Is-Check" /> <?=$item['cbContactNameR'];?> <?=$item['cbContactLNameR'];?></span> <span>&nbsp; &nbsp;<?=$item['cbDateTime'];?></span></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4" >
            <div class="panel  panel-default" style="font-size:12px">
                <div class="panel-heading" style="background-color: #2a6496;color: #fff "><strong><a style="color: white" href='#'>Technical Tests</></a></strong></div>
                <div class="panel-body"  style="<?=$height?>" >
                    <span id="technical-test">
                    <?php
                    if(!empty($this->resultTestList) && count($this->resultTestList)){
                        foreach($this->resultTestList as $kk=>$resultTestListInfo){
                            ?>
                            <span class="label-tag pull-left"><?=$resultTestListInfo['TestName']?> <i class="glyphicon glyphicon-remove text-right tag-remove" onclick="javascript:objdb.deleteTest(<?=$resultTestListInfo['TestID']?>)"></i></span>
                     <?php   }
                    }
                    ?>
                    </span>
                    <p class="pull-left" style="width: 100%;position: absolute;bottom: 20px;">
                        <button class="btn btn-primary" onclick="window.location.href='#'">Create New Test</button>
                    </p>
                </div>

            </div>
        </div>
    </div>

    <div class="panel-group" id="accordion" style="font-size:12px">

        <div class="panel panel-default">
            <div class="panel-heading" style="background-color: #2a6496;color: #fff">
                <h4 class="panel-title" style="font-size:12px">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                        <strong>Recently Posted Opportunities</strong>
                    </a>
                </h4>
            </div>

        </div>
        <!-- career list-->
        <div class="tab-pane active" >
            <table class="table table-striped  table-stripedgray table-bordered" cellspacing="0" width="100%" style="border-top-color: #eeeeee">
                <thead>
                <tr role="row" style="background-color: #eeeeee">
                    <th style="width:135px">
                        <label>
                            <input type="checkbox"> Select All
                        </label>
                    </th>
                    <th style="width:135px">
                        <label>
                            Opportunity Title
                        </label>
                    </th>
                    <th style="width:125px">
                        <label>
                            Technical Skills
                        </label>
                    </th>
                    <th>
                        <label>
                            Opportunity Description
                        </label>
                    </th>
                    <th style="width:125px">
                        <label>
                            Require Tests
                        </label>
                    </th>
                    <th style="width:100px">
                        <label>
                            Status
                        </label>
                    </th>
                    <th style="text-left: right; padding-left:10px;width:120px">
                        <div class="btn-group"> <label> Action </label>
                            <!--
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="border-color: #eeeeee; background-color: #eeeeee">
                            Action
                               <span class="caret"></span>
                            </button>
                            <ul id="menu-privacy" class="dropdown-menu" role="menu">
                                <li><a  href="javascript: void(0);">Insert</a></li>
                                <li><a  href="javascript: void(0);">Update</a></li>
                                <li><a  href="javascript: void(0);">Delete</a></li>
                            </ul> -->
                        </div>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php
                if(!empty($oppportunityList)){
                    foreach ($oppportunityList as $k=>$info) {
                        $skillName ="";
                        $testName ="";
                        foreach($info['Skills'] as $skID=>$skName){
                            $skillName = $skillName.'<span>'. $skName['SkillName']. '</span>'."  ";
                        }
                        foreach($info['Tests'] as $t=>$tName){
                            $testName = $testName .'<span>'. $tName['TestName']. '</span>'."  ";
                        }
                        if($info['status']== 1){
                            $active = "Active";
                            $color = '#7aac34';
                        } else {
                            $active = "Close";
                            $color = '#ccc';
                        }
                        ?>
                        <tr role="row" class="odd">
                            <td>
                                <input type="checkbox" style="margin:0">&nbsp;<?=$info['posteddate']?><!--<span style="float:right; padding-top:3px; color:#cccccc" class="glyphicon glyphicon-eye-open" ></span>-->
                            </td>
                            <td><?=$info['title']?></td>
                            <td><?=$skillName?></td>
							<?php
								 $words = explode(" ",$info['careerdescription']);
								 $str= implode(" ",array_splice($words,0,57));
							?>
                            <td><?=$str." ..."?></td>
                            <td ><?=$testName?></td>
                            <td style="color: <?=$color?>; font-weight: bold" class="opportunity-active">
                                <?=$active?>
                            </td>
                            <td align="left" style="cursor: pointer">

					<?php
                                $id=$info['OpportunityID'];
                                ?>

								<div id="modaleye" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">

								  <div class="modal-dialog modal-sm">
									<div class="modal-content" style="height:50px;width:350px">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
									  <div style="text-align:center;margin-top:15px">Don't have yet.</div>
									</div>
								  </div>
								</div>

								<a id="Test"  href="javascript: void(0);" data-container="body" data-toggle="popover" data-placement="top" data-content="Don't have yet."><span style="float:left; padding-top:2px; color:#cccccc" class="glyphicon glyphicon-eye-open"></span></a>
								<input type="hidden" id='<?=$info['OpportunityID']?>'>

								<a href="#">
                                    <span class="glyphicon glyphicon-credit-card edit-career-btn" style="color:#7aac34; text-indent: 15px;float:left; padding-top:2px;"></span>
                                </a>
								<span class="glyphicon glyphicon-star publib-notication" style="padding-left:15px;color:#c77405;float:left; padding-top:1px;" opportunityattr="<?=$id?>"></span>
								<!--<span style=" color:#fff; padding-left:12px" class="glyphicon glyphicon-remove delete-career-btn"></span>-->
							</td>
                        </tr>
                    <?php } }
                else{
                    echo '<tr role="row" class="odd" ><td colspan="7">No record</td> </tr>';
                }?>
                </tbody>
            </table>


        </div>
        <!--career list end-->
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function () {
		$("a#Test").click(function(){

		  $('#modaleye').modal('show')

		});
        $("#nav li").removeClass("active");//this will remove the active class from previously active menu item
        $('#dasboard-test').addClass('active');
        $('#addReceiveEmail').unbind('click').bind('click',objdb.addReceiveEmail);
        $('#test-act-remove').unbind('click').bind('click',objdb.deleletNoticcationCheck)
        $('#Index-Check-All').unbind('click').bind('click',objdb.IndexCheckedAll)
        $('.Index-Is-Check').unbind('click').bind('click',objdb.IndexIsChecked);
        $('.publib-notication').unbind('click').bind('click',objdb.publibOpportunity);
        $('.cancel-notification').unbind('click').bind('click',function(){
            $("#form-addnotification #toTheseEmail").text("");
            $("#form-addnotification #subjectNotification").val("");
            $("#form-addnotification #contentNotification").val("");
        });
    });

</script>