<?php
$helper = $this->layout()->_helper;
$educationList = $this->list;
$core = new PR_Api_Core_CandidateClass();
$getUserArray=$this->client;
$getCandidates=$this->getCandidates;

?>
<style>
    .btn-edit:hover{cursor: pointer;text-decoration: underline}
    .qst-remove{color: #bbb}
    .qst-remove:hover{color: #333; cursor: pointer}
    ul#nav-left{margin:0;padding:7px 0;margin-bottom: 10px;list-style: none; border-top: 1px solid #bbb;border-bottom: 1px solid #bbb}
    ul#nav-left li{line-height: 35px;}
    ul#nav-left a{color: #777}
    ul#nav-left .active{color: #428bca}


        /****/

    .breadcrumb {
        width: 100%;
        /*centering*/
        padding:3px;
        border: 1px solid #ddd;
        display: inline-block;
        /*box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.35);*/
        /*overflow: hidden;*/
        /*border-radius: 5px;*/
        /*Lets add the numbers for each link using CSS counters. flag is the name of the counter. to be defined using counter-reset in the parent element of the links*/
        counter-reset: flag;
    }

    .breadcrumb a {
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        outline: none;
        display: block;
        float: left;
        font-size: 12px;
        line-height: 36px;
        color: white;
        /*need more margin on the left of links to accomodate the numbers*/
        padding: 0 30px;
        background: #666;
        background: linear-gradient(#666, #333);
        position: relative;
    }
        /*since the first link does not have a triangle before it we can reduce the left padding to make it look consistent with other links*/
    .breadcrumb a:first-child {
        padding-left: 46px;
        border-radius: 5px 0 0 5px; /*to match with the parent's radius*/
    }
    .breadcrumb a:first-child:before {
        left: 14px;
    }
    .breadcrumb a:last-child {
        border-radius: 0 5px 5px 0; /*this was to prevent glitches on hover*/
        padding-right: 20px;
    }

        /*hover/active styles*/
    .breadcrumb a.active, .breadcrumb a:hover{
        background: #333;
        background: linear-gradient(#333, #000);
    }
    .breadcrumb a.active:after, .breadcrumb a:hover:after {
        background: #333;
        background: linear-gradient(135deg, #333, #000);
    }

        /*adding the arrows for the breadcrumbs using rotated pseudo elements*/
    .breadcrumb a:after {
        content: '';
        position: absolute;
        top: 0;
        right: -18px; /*half of square's length*/
        /*same dimension as the line-height of .breadcrumb a */
        width: 36px;
        height: 36px;
        /*as you see the rotated square takes a larger height. which makes it tough to position it properly. So we are going to scale it down so that the diagonals become equal to the line-height of the link. We scale it to 70.7% because if square's:
        length = 1; diagonal = (1^2 + 1^2)^0.5 = 1.414 (pythagoras theorem)
        if diagonal required = 1; length = 1/1.414 = 0.707*/
        transform: scale(0.707) rotate(45deg);
        /*we need to prevent the arrows from getting buried under the next link*/
        z-index: 1;
        /*background same as links but the gradient will be rotated to compensate with the transform applied*/
        background: #666;
        background: linear-gradient(135deg, #666, #333);
        /*stylish arrow design using box shadow*/
        box-shadow:
            /*2px -2px 0 2px rgba(0, 0, 0, 0.4),3px -3px 0 2px rgba(255, 255, 255, 0.1);*/
            2px -2px 0 2px #bbb,
            3px -3px 0 2px #eee;
        /*
            5px - for rounded arrows and
            50px - to prevent hover glitches on the border created using shadows*/
        border-radius: 0 5px 0 50px;
    }
        /*we dont need an arrow after the last link*/
    .breadcrumb a:last-child:after {
        content: none;
    }
        /*we will use the :before element to show numbers*/
    .breadcrumb a:before {
        /*content: counter(flag);*/
        /*counter-increment: flag;*/
        /*some styles now*/
        border-radius: 100%;
        width: 20px;
        height: 20px;
        line-height: 20px;
        margin: 8px 0;
        position: absolute;
        top: 0;
        left: 30px;
        background: #444;
        background: linear-gradient(#444, #222);
        font-weight: bold;
    }


    .flat a, .flat a:after {
        background: white;
        color: black;
        transition: all 0.5s;
    }
    .flat a:before {
        background: white;
        box-shadow: 0 0 0 1px #ccc;
    }
    .flat a:hover, .flat a.active,
    .flat a:hover:after, .flat a.active:after{
        background: #2a6496; color: #fff;
    }
     .logo{
       /* background: url('<?=URL_THEMES?>images/avatar_none.jpg') no-repeat ;*/
       <?php
        $image=URL_MEDIA_PHOTO.$getCandidates["image"];
       ?>
       background: url('<?php if(!empty($getCandidates["image"])) echo  $image; else echo URL_THEMES."images/avatar_none.jpg";?>') no-repeat;
        width: 211px;
        height: 165px;
    }

        /****/

</style>
<div class="container">

    <div class="row" style="padding-top: 40px;">
        <div class="col-md-3">
        <div class="text-center">
                <div class="logo"><a href="<?= URL_BASE ?>candidate/upload-photo"><img src="<?=URL_THEMES?>images/bg_grey_text.png" style="float:right;padding-top:140px;"></a></div>

            </div>
            <span  style="font-size: 12px;color: #005595;"><?= $getUserArray["emailaddress"]?></span><br/>
            <span style="font-weight:bold;font-size:13px">View my profile</span> <br/>
            <span>
                <img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span style="font-size:13px;padding-left:5px"><?=$getUserArray["Country"]?><?php if($getUserArray["Country"]=="") echo "United State";?></span><span style="padding-left:5px;font-size:13px" class=""><?=$getUserArray["Address1"]?><?php if($getUserArray["Address1"]!="") echo ", "; ?> <?=$getUserArray["State"]?></span>
            </span>
            <br><span><strong style="font-size:13px">Expected Salary: <?=$getCandidates["minimumsalary"]?><?php if($getCandidates["minimumsalary"]!="") echo "-";?><?=$getCandidates["maximumsalary"]?><?php if($getCandidates["maximumsalary"]!="")echo "K";?></strong></span><br/>
            <p style="padding: 10px 0">
                <!--<i class="lbl-log">Edit</i>>-->
                <a href="<?= URL_BASE ?>candidate/editoverview"><img src="<?=URL_THEMES?>images/btn_edit.png"></a>
            </p>
            <ul id="nav-left">
                <li><a href="<?=$helper->url('profile-builder?utm_source=contact','candidate');?>" class="active"><strong>Profile builder</strong></a></li>
                <li><a href="<?=$helper->url('profile','candidate');?>">Overview</a></li>
                <li><a href="<?=$helper->url('contact-info','candidate');?>">Contact Info</a></li>
				<li><a href="<?=$helper->url('employment','candidate');?>">Employment</a></li>
                <li><a href="<?=$helper->url('portfolio','candidate');?>">Portfolio</a></li>
                <li><a href="<?=$helper->url('vieweducation','candidate');?>">Education</a></li>
                <li><a href="<?=$helper->url('skills?utm_source=index','candidate');?>">Skills</a></li>
                <li><a href="<?=$helper->url('references','candidate');?>">References</a></li>
                <li><a href="<?=$helper->url('skilltest','candidate');?>">Tests</a></li>
                <li><a href="<?=$helper->url('interest','candidate');?>">Interest</a></li>
            </ul>
             <p style="font-size:13px;color:#777">Last signed: <?= date('M d, Y',strtotime($getUserArray["Lastsigned"])) ?></p>
        </div>
        <div class="col-md-9">
            <div class="page-header" style="color: #2a6496 ;margin-top:0">
                <h2  style="color: #2a6496 ;margin-top:0"><span class="glyphicon glyphicon-briefcase"></span> <strong>Profile Builder</strong></h2>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="breadcrumb flat">
                        <a href="<?=$helper->url('profile-builder?utm_source=contact','candidate');?>" <?=$this->step =='contact'? 'class="active"':'';?>>Contact Info</a>
                        <a href="<?=$helper->url('profile-builder?utm_source=education','candidate');?>" <?=$this->step =='education'? 'class="active"':'';?>>Education</a>
                        <a href="<?=$helper->url('profile-builder?utm_source=employment','candidate');?>" <?=$this->step =='employment'? 'class="active"':'';?>>Employment</a>
                        <a href="<?=$helper->url('profile-builder?utm_source=skills','candidate');?>"  <?=$this->step =='skills'? 'class="active"':'';?>>Skills</a>
                        <a href="<?=$helper->url('profile-builder?utm_source=portfolio','candidate');?>" <?=$this->step =='portfolio'? 'class="active"':'';?>>Portfolio</a>
                        <span class="pull-right" style="position: relative;vertical-align: bottom;font-weight: bold;margin: 7px 10px auto auto"><?=$this->stepCount;?></span>
                    </div>
                    <div class="col-md-9" style="padding-left:0;">
                        <form id="education-form" role="form">
                            <input type="hidden" name="eduId" id="eduId"/>
                            <div class="form-group">
                                <label>Institution Name (no abbreviations,please)</label>
                                <input name="inst-name" type="text" class="form-control"  placeholder="">
                            </div>
                            <div class="form-group">
                                <label>Name and Type of Degree Name (no abbreviations,please)</label>
                                <input name="degree-name"  type="text" class="form-control" placeholder="">
                            </div>
                            <div class="col-md-6" style="margin:0;padding:0 50px 0 0">
                                <div class="form-group">
                                    <label> <strong>Start Year</strong></label>
                                    <div class="input-group date" id="datetimepicker8">
                                        <input type="text" name="start-year" class="form-control">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6" style="margin:0;padding: 0 50px 0 0">
                                <div class="form-group">
                                    <label> <strong>End Year</strong></label>
                                    <div class="input-group date" id="datetimepicker9">
                                        <input type="text" name="end-year" class="form-control">
                                    <span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span>
                                    </span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <button data-status="add" data-step="education" id="add-another" data-loading-text="Loading..." type="button" class="btn btn-sm btn-success" type="button"><strong> + Add Another</strong></button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <div class="pull-right">
                            <button class="btn btn-sm btn-default" type="button" id="cmd-back1" data-back="contact"><strong><i class="glyphicon glyphicon-chevron-left"></i></strong></button>
                            <button class="btn btn-sm btn-success" type="button" data-next="employment" id="cmd-next1"><strong><i class="glyphicon glyphicon-chevron-right"></i></strong></button>
                        </div>
                    </div>
                    <div class="col-md-12" style="padding-left:0">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <strong>Education List</strong>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table id="education-list" class="table">
                                        <thead>
                                        <tr>
                                            <th>Institution Name</th>
                                            <th>Name and Type of Degree Name</th>
                                            <th>Start Year</th>
                                            <th>End Year</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php

                                            foreach($educationList as $item){


                                                $idx = 0;
                                                $startYear = null;
                                                $endYear = null;
                                                if (($timestamp = strtotime($item['startdate'])) !== false)
                                                    $startYear = date("Y", $timestamp);
                                                if (($timestamp = strtotime($item['enddate'])) !== false)
                                                    $endYear = date("Y", $timestamp);
                                                $detailEducation = $core->getCandidateEducation($item['CredentialExperienceID']);
                                        ?>
                                            <tr>
                                            <td><?=$item['institution_name'];?></td>
                                            <td><?=$detailEducation['title'];?></td>
                                            <td><?=$startYear;?></td>
                                            <td><?=$endYear;?></td>
                                            <td>
                                                <span class="btn-edit" data-id="<?=$item['CredentialExperienceID'];?>" style="color: #4cae4c"><strong>Edit</strong></span> &nbsp;&nbsp;
                                                <span><i data-text="<?=$item['institution_name'];?>" data-id="<?=$item['CredentialExperienceID'];?>" class="glyphicon glyphicon-remove qst-remove"></i></span>
                                            </td>
                                            </tr>
                                        <?php $idx = $idx + 1;} ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <div style="margin-top: 30px">
                            <button id="cmd-back" data-back="contact" class="btn btn-default" type="button"><strong>Back</strong></button> &nbsp;
                            <!--<button class="btn btn-default disabled" type="button"><strong>Skip</strong></button> &nbsp;-->
                            <button id="cmd-next" type="button" data-next="employment" class="btn btn-success" type="button"><strong>Next</strong></button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?=URL_THEMES;?>js/pocket.candidate.js?vs=1"></script>
 <script type="text/javascript">
    $("#datetimepicker8").datepicker({ autoclose: true, todayHighlight: true,format: " yyyy",viewMode: "years",minViewMode: "years"});
    $("#datetimepicker9").datepicker({ autoclose: true, todayHighlight: true,format: " yyyy",viewMode: "years",minViewMode: "years"});
    var prCandidate= new pocketCandidate();
    $('#education-list .btn-edit').unbind('click').bind('click',prCandidate.editEducation);
    $('#education-list .qst-remove').unbind('click').bind('click',prCandidate.deleteEducation);


</script>