<?php
$helper = $this->layout()->_helper;
$getUserArray=$this->client;
$getCandidates=$this->getCandidates;
?>
<style>
    .btn-edit:hover{cursor: pointer;text-decoration: underline}
    .qst-remove{color: #bbb}
    .qst-remove:hover{color: #333; cursor: pointer}

    ul#nav-left{margin:0;padding:7px 0;margin-bottom: 10px;list-style: none; border-top: 1px solid #bbb;border-bottom: 1px solid #bbb}
    ul#nav-left li{line-height: 35px;}
    ul#nav-left a{color: #777}
    ul#nav-left .active{color: #428bca}


        /****/

    .breadcrumb {
        width: 100%;
        /*centering*/
        padding:3px;
        border: 1px solid #ddd;
        display: inline-block;
        /*box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.35);*/
        /*overflow: hidden;*/
        /*border-radius: 5px;*/
        /*Lets add the numbers for each link using CSS counters. flag is the name of the counter. to be defined using counter-reset in the parent element of the links*/
        counter-reset: flag;
    }

    .breadcrumb a {
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        outline: none;
        display: block;
        float: left;
        font-size: 12px;
        line-height: 36px;
        color: white;
        /*need more margin on the left of links to accomodate the numbers*/
        padding: 0 30px;
        background: #666;
        background: linear-gradient(#666, #333);
        position: relative;
    }
        /*since the first link does not have a triangle before it we can reduce the left padding to make it look consistent with other links*/
    .breadcrumb a:first-child {
        padding-left: 46px;
        border-radius: 5px 0 0 5px; /*to match with the parent's radius*/
    }
    .breadcrumb a:first-child:before {
        left: 14px;
    }
    .breadcrumb a:last-child {
        border-radius: 0 5px 5px 0; /*this was to prevent glitches on hover*/
        padding-right: 20px;
    }

        /*hover/active styles*/
    .breadcrumb a.active, .breadcrumb a:hover{
        background: #333;
        background: linear-gradient(#333, #000);
    }
    .breadcrumb a.active:after, .breadcrumb a:hover:after {
        background: #333;
        background: linear-gradient(135deg, #333, #000);
    }

        /*adding the arrows for the breadcrumbs using rotated pseudo elements*/
    .breadcrumb a:after {
        content: '';
        position: absolute;
        top: 0;
        right: -18px; /*half of square's length*/
        /*same dimension as the line-height of .breadcrumb a */
        width: 36px;
        height: 36px;
        /*as you see the rotated square takes a larger height. which makes it tough to position it properly. So we are going to scale it down so that the diagonals become equal to the line-height of the link. We scale it to 70.7% because if square's:
        length = 1; diagonal = (1^2 + 1^2)^0.5 = 1.414 (pythagoras theorem)
        if diagonal required = 1; length = 1/1.414 = 0.707*/
        transform: scale(0.707) rotate(45deg);
        /*we need to prevent the arrows from getting buried under the next link*/
        z-index: 1;
        /*background same as links but the gradient will be rotated to compensate with the transform applied*/
        background: #666;
        background: linear-gradient(135deg, #666, #333);
        /*stylish arrow design using box shadow*/
        box-shadow:
            /*2px -2px 0 2px rgba(0, 0, 0, 0.4),3px -3px 0 2px rgba(255, 255, 255, 0.1);*/
            2px -2px 0 2px #bbb,
            3px -3px 0 2px #eee;
        /*
            5px - for rounded arrows and
            50px - to prevent hover glitches on the border created using shadows*/
        border-radius: 0 5px 0 50px;
    }
        /*we dont need an arrow after the last link*/
    .breadcrumb a:last-child:after {
        content: none;
    }
        /*we will use the :before element to show numbers*/
    .breadcrumb a:before {
        /*content: counter(flag);*/
        /*counter-increment: flag;*/
        /*some styles now*/
        border-radius: 100%;
        width: 20px;
        height: 20px;
        line-height: 20px;
        margin: 8px 0;
        position: absolute;
        top: 0;
        left: 30px;
        background: #444;
        background: linear-gradient(#444, #222);
        font-weight: bold;
    }


    .flat a, .flat a:after {
        background: white;
        color: black;
        transition: all 0.5s;
    }
    .flat a:before {
        background: white;
        box-shadow: 0 0 0 1px #ccc;
    }
    .flat a:hover, .flat a.active,
    .flat a:hover:after, .flat a.active:after{
        background: #2a6496; color: #fff;
    }
    .logo{
       /* background: url('<?=URL_THEMES?>images/avatar_none.jpg') no-repeat ;*/
       <?php
        $image=URL_MEDIA_PHOTO.$getCandidates["image"];
       ?>
       background: url('<?php if(!empty($getCandidates["image"])) echo  $image; else echo URL_THEMES."images/avatar_none.jpg";?>') no-repeat;
        width: 211px;
        height: 165px;
    }
        /****/

</style>
<div class="container">

    <div class="row" style="padding-top: 40px;">
        <div class="col-md-3">
             <div class="text-center">
                <div class="logo"><a href="<?= URL_BASE ?>candidate/upload-photo"><img src="<?=URL_THEMES?>images/bg_grey_text.png" style="float:right;padding-top:140px;"></a></div>

            </div>
            <span  style="font-size: 12px;color: #005595;"><?= $getUserArray["emailaddress"]?></span><br/>
            <span style="font-weight:bold;font-size:13px">View my profile</span> <br/>
            <span>
                <img src="<?=URL_THEMES?>images/USA_flag.jpg"></span><span style="font-size:13px;padding-left:5px"><?=$getUserArray["Country"]?><?php if($getUserArray["Country"]=="") echo "United State";?></span><span style="padding-left:5px;font-size:13px" class=""><?=$getUserArray["Address1"]?><?php if($getUserArray["Address1"]!="") echo ", "; ?> <?=$getUserArray["State"]?></span>
            </span>
            <br><span><strong style="font-size:13px">Expected Salary: <?=$getCandidates["minimumsalary"]?><?php if($getCandidates["minimumsalary"]!="") echo "-";?><?=$getCandidates["maximumsalary"]?><?php if($getCandidates["maximumsalary"]!="")echo "K";?></strong></span><br/>
            <p style="padding: 10px 0">
                <!--<i class="lbl-log">Edit</i>>-->
                <a href="<?= URL_BASE ?>candidate/editoverview"><img src="<?=URL_THEMES?>images/btn_edit.png"></a>
            </p>
            <ul id="nav-left">
                <li><a href="<?=$helper->url('profile-builder?utm_source=contact','candidate');?>" class="active"><strong>Profile builder</strong></a></li>
                <li><a href="<?=$helper->url('profile','candidate');?>">Overview</a></li>
                <li><a href="<?=$helper->url('contact-info','candidate');?>">Contact Info</a></li>
				<li><a href="<?=$helper->url('employment','candidate');?>">Employment</a></li>
                <li><a href="<?=$helper->url('portfolio','candidate');?>">Portfolio</a></li>
                <li><a href="<?=$helper->url('vieweducation','candidate');?>">Education</a></li>
                <li><a href="<?=$helper->url('skills?utm_source=index','candidate');?>">Skills</a></li>
                <li><a href="<?=$helper->url('references','candidate');?>">References</a></li>
                <li><a href="<?=$helper->url('skilltest','candidate');?>">Tests</a></li>
                <li><a href="<?=$helper->url('interest','candidate');?>">Interest</a></li>
            </ul>
            <p>Last signed: Nov,8,2014</p>
        </div>
        <div class="col-md-9">
            <div class="page-header" style="color: #2a6496 ;margin-top:0">
                <h2  style="color: #2a6496 ;margin-top:0"><span class="glyphicon glyphicon-briefcase"></span> <strong>Profile Builder</strong></h2>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="breadcrumb flat">
                        <a href="<?=$helper->url('profile-builder?utm_source=contact','candidate');?>" <?=$this->step =='contact'? 'class="active"':'';?>>Contact Info</a>
                        <a href="<?=$helper->url('profile-builder?utm_source=education','candidate');?>" <?=$this->step =='education'? 'class="active"':'';?>>Education</a>
                        <a href="<?=$helper->url('profile-builder?utm_source=employment','candidate');?>" <?=$this->step =='employment'? 'class="active"':'';?>>Employment</a>
                        <a href="<?=$helper->url('profile-builder?utm_source=skills','candidate');?>"  <?=$this->step =='skills'? 'class="active"':'';?>>Skills</a>
                        <a href="<?=$helper->url('profile-builder?utm_source=portfolio','candidate');?>" <?=$this->step =='portfolio'? 'class="active"':'';?>>Portfolio</a>
                        <span class="pull-right" style="position: relative;vertical-align: bottom;font-weight: bold;margin: 7px 10px auto auto"><?=$this->stepCount;?></span>
                    </div>
                    <div class="col-md-9" style="padding-left:0;">

                        <form id="portfolio-form" role="form">
                            <input type="hidden" value="" name="portId" id="empId"/>
                            <div class="form-group">
                                <label>Title</label>
                                <input name="title" type="text" class="form-control" placeholder="">
                            </div>
                            <div class="form-group">
                                <label>URL (if any)</label>
                                <input name="url"  type="text" class="form-control" placeholder="">
                                <img style="width: 20px;height: 20px; display: none" id="imgTest"/>
                            </div>
                            <div class="form-group">
                                <label><strong>Description (optional)</strong></label>

                                <textarea id="portDesc" name="description" class="form-control"></textarea>
                            </div>


                            <div class="form-group">
                                <button data-status="add" data-step="portfolio" id="add-another" data-loading-text="Loading..." type="button" class="btn btn-sm btn-success" type="button"><strong> + Add Another</strong></button>
                            </div>

                        </form>

                    </div>

                    <div class="col-md-3">
                        <div class="pull-right">
                            <button class="btn btn-sm btn-default" type="button" id="cmd-back1" data-back="skills"><strong><i class="glyphicon glyphicon-chevron-left"></i></strong></button>
                            <button class="btn btn-sm btn-success" type="button" id="cmd-next1" data-next="success"><strong><i class="glyphicon glyphicon-chevron-right"></i></strong></button>
                        </div>
                    </div>
                    <div class="col-md-9" style="padding-left:0">
                        <div class="panel panel-default">

                            <!-- /.panel-heading -->
                            <div class="panel-body">
                                <div class="table-responsive">

                                    <table id="portfolioList" class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th><input type="checkbox" id="port-check-all"/></th>
                                            <th colspan="2">
                                                <i class="lbl-log" id="port-deletes">Delete</i> &nbsp;
                                                <i class="pull-right">(<?=count($this->list);?> Uploaded)</i>
                                                <span class="dropdown lbl-log">
                                                    <span href="#" data-toggle="dropdown" class="dropdown-toggle">
                                                        <strong>More Action</strong><span class="caret"></span>
                                                    </span>
                                                    <ul role="menu" class="dropdown-menu">
                                                        <li><a id="port-edit" href="javascript: void(0)">Edit</a></li>
                                                        <li><a id="port-delete" href="javascript: void(0);">Delete</a></li>
                                                    </ul>
                                                </span>
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach($this->list as $key=>$item){ ?>
                                            <tr>
                                                <td><input data-text="<?=$item['Title'];?>" type="checkbox" name="" data-id="<?=$item['CandidatePortfolioID'];?>"/></td>
                                                <td>
                                                <!--<img width="100px" height="80px" src="<?=$item['URL'];?>" alt="" title=""/>-->
                                                 <iframe class="embed-responsive-item" frameborder="0" width="100px" height="80px" src="<?=$item["URL"]?>" scrolling="no"></iframe>
                                                </td>
                                                <td>
                                                <?php
                                                $words = explode(" ",$item['Description']); 
                                                $str= implode(" ",array_splice($words,0,18));
                                                ?>
                                                    <h5 style="margin:0;padding:0;"><label><?=$item['Title'];?></label></h5>
                                                    <p style="color: #777;margin:0;padding:0;"><?=$str;?></p>
                                                </td>
                                                <td style="margin:0;padding:0">
                                                    <a><img src="<?=URL_THEMES;?>images/btn_green.png"/></a>
                                                </td>
                                            </tr>
                                        <?php } ?>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div style="margin-top: 30px">
                            <button id="cmd-back" data-back="skills" class="btn btn-default" type="button"><strong>Back</strong></button> &nbsp;
                           <!-- <button class="btn btn-default disabled" type="button"><strong>Skip</strong></button> &nbsp;-->
                            <button id="cmd-next" data-next="success" type="button" class="btn btn-success" type="button"><strong>Next</strong></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?=URL_THEMES;?>js/pocket.candidate.js?vs=1"></script>
<script>
    var prCandidate= new pocketCandidate();
    $('#portfolioList #port-delete').unbind('click').bind('click',prCandidate.deletePortfolio);
    $('#portfolioList #port-deletes').unbind('click').bind('click',prCandidate.deletePortfolio);
    $('#portfolioList #port-edit').unbind('click').bind('click',prCandidate.editPortfolio);
    $('#portfolioList #port-check-all').unbind('change').bind('change',prCandidate.portfolioCheckAll);

</script>